apiVersion: v1
kind: Service
metadata:
  name: self-healing-service
  namespace: self-healing-app
  labels:
    app: self-healing-service
    app.kubernetes.io/name: self-healing-k8s-service
spec:
  type: NodePort
  selector:
    app: self-healing-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
